import re
import csv

def get_idd_classes(idd_field_list_file):
    """
    Read the case-sensitive class names from a CSV file based on EnergyPlus IDD.
    """
    # Assume CSV file has columns:
    # klass,index,field_name,is_autosizable,default_value,units
    # read the unique values from klass column
    klasses = set()
    with open(idd_field_list_file,'r') as f:
        reader = csv.DictReader(f)
        for line in reader:
            klasses.add(line['klass'])
    return klasses

def stylize_sizing_map(sizing_map_file, klasses, output_file):
    # prepare a list of string substitutions of the form (klass_ucase, klass)
    # where klass_ucase is the upper case version of the class name (as generated by modelkit original script)
    replace_list = [(klass.upper(), klass) for klass in klasses]

    # get all the text from the file
    with open(sizing_map_file, 'r') as f:
        text = f.read()
    # apply each substitution pattern
    for klass_ucase, klass in replace_list:
        text = re.sub(klass_ucase, klass, text)

    #print(text[:500])

    with open(output_file,'w') as f:
        f.write(text)

if __name__ == "__main__":
    idd_field_list_file = 'idd_fields_22-2.csv'
    sizing_map_file = '22-2.csv'
    output_file = 'stylized.22-2.csv'
    klasses = get_idd_classes(idd_field_list_file)
    print(f"Found {len(klasses)} unique klasses")
    stylize_sizing_map(sizing_map_file, klasses, output_file)
    print(f"Wrote stylized sizing map to {output_file}.")
