--SET search_path TO "MC_results_database";
CREATE TABLE IF NOT EXISTS "sim_annual" (
"TechID"  VARCHAR(255) NOT NULL,
"SizingID"  VARCHAR(255) NOT NULL,
"BldgType"  VARCHAR(255) NOT NULL,
"BldgVint"  VARCHAR(255) NOT NULL,
"BldgLoc"  VARCHAR(255) NOT NULL,
"BldgHVAC"  VARCHAR(255) NOT NULL,
"tstat"  SMALLINT NOT NULL,
"normunit"  VARCHAR(255) NOT NULL,
"numunits"  REAL,
"measarea"  REAL,
"kwh_tot"  REAL,
"kwh_ltg"  REAL,
"kwh_task"  REAL,
"kwh_equip"  REAL,
"kwh_htg"  REAL,
"kwh_clg"  REAL,
"kwh_twr"  REAL,
"kwh_aux"  REAL,
"kwh_vent"  REAL,
"kwh_venthtg"  REAL,
"kwh_ventclg"  REAL,
"kwh_refg"  REAL,
"kwh_hpsup"  REAL,
"kwh_shw"  REAL,
"kwh_ext"  REAL,
"thm_tot"  REAL,
"thm_equip"  REAL,
"thm_htg"  REAL,
"thm_shw"  REAL,
"deskw_ltg"  REAL,
"deskw_equ"  REAL,
"lastmod"  TIMESTAMP(6),
PRIMARY KEY ("TechID", "SizingID", "BldgType", "BldgVint", "BldgLoc", "BldgHVAC", "tstat", "normunit")
);
