--SET search_path TO "MC_results_database";
CREATE TABLE IF NOT EXISTS "sfm_annual" (
"TechID"  VARCHAR(255) NOT NULL,
"SizingID"  VARCHAR(255) NOT NULL,
"BldgType"  VARCHAR(255) NOT NULL,
"BldgVint"  VARCHAR(255) NOT NULL,
"BldgLoc"  VARCHAR(255) NOT NULL,
"BldgHVAC"  VARCHAR(255) NOT NULL,
"tstat"  SMALLINT NOT NULL,
"normunit"  VARCHAR(255) NOT NULL,
"numunits"  REAL,
"kwh_tot1"  REAL NOT NULL,
"kwh_ltg1"  REAL,
"kwh_task1"  REAL,
"kwh_equip1"  REAL,
"kwh_htg1"  REAL,
"kwh_clg1"  REAL,
"kwh_twr1"  REAL,
"kwh_aux1"  REAL,
"kwh_vent1"  REAL,
"kwh_venthtg1a"  REAL,
"kwh_ventclg1a"  REAL,
"kwh_venthtg1b"  REAL,
"kwh_ventclg1b"  REAL,
"kwh_refg1"  REAL,
"kwh_hpsup1"  REAL,
"kwh_shw1"  REAL,
"kwh_ext1"  REAL,
"thm_tot1"  REAL,
"thm_equip1"  REAL,
"thm_htg1"  REAL,
"thm_shw1"  REAL,
"kwh_tot2"  REAL NOT NULL,
"kwh_ltg2"  REAL,
"kwh_task2"  REAL,
"kwh_equip2"  REAL,
"kwh_htg2"  REAL,
"kwh_clg2"  REAL,
"kwh_twr2"  REAL,
"kwh_aux2"  REAL,
"kwh_vent2"  REAL,
"kwh_venthtg2a"  REAL,
"kwh_ventclg2a"  REAL,
"kwh_venthtg2b"  REAL,
"kwh_ventclg2b"  REAL,
"kwh_refg2"  REAL,
"kwh_hpsup2"  REAL,
"kwh_shw2"  REAL,
"kwh_ext2"  REAL,
"thm_tot2"  REAL,
"thm_equip2"  REAL,
"thm_htg2"  REAL,
"thm_shw2"  REAL,
"lastmod"  TIMESTAMP(6),
PRIMARY KEY ("TechID", "SizingID", "BldgType", "BldgVint", "BldgLoc", "BldgHVAC", "tstat", "normunit")
);
